swagger: "2.0"
info:
  description: API REST used for educational purposes and testing
  version: 1.0.0
  title: Alphabetic users API REST
host: localhost
basePath: /api/users
schemes:
- https
paths:
  /users:
    get:
      tags:
      - Endpoints
      description: It gives all the active users on alphabetic order
      produces:
      - application/json
      parameters: []
      responses:
        200:
          description: OK
          schema:
            type: object
            properties:
              users:
                type: array
                items:
                  $ref: '#/definitions/inline_response_200_users'
        400:
          description: Bad Request
          schema:
            type: object
            properties:
              error:
                type: string
              severity:
                type: string
              message:
                type: string
        401:
          description: Unauthorized
          schema:
            type: object
            properties:
              error:
                type: string
              severity:
                type: string
              message:
                type: string
        404:
          description: Not Found
          schema:
            type: object
            properties:
              error:
                type: string
              severity:
                type: string
              message:
                type: string
        500:
          description: Internal Server Error
          schema:
            type: object
            properties:
              error:
                type: string
              severity:
                type: string
              message:
                type: string
definitions:
  inline_response_200_users:
    properties:
      id:
        type: integer
      name:
        type: string
      lastname:
        type: string
      birthday:
        type: string
        format: date
      is_active:
        type: boolean
      email:
        type: string
      genre:
        type: string
      age:
        type: integer  
  inline_response_200:
    properties:
      users:
        type: array
        items:
          $ref: '#/definitions/inline_response_200_users'
  inline_response_400:
    properties:
      error:
        type: string
      severity:
        type: string
      message:
        type: string
